'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getBrowserSupabase } from '@/lib/supabase/browser';

type Lead = { id:string; reference_number:string; job_type:string; service_type:string; description:string; urgency:string; customer_name:string; customer_email:string; customer_phone:string; preferred_contact:string; street:string; city:string; state:string; zip:string; preferred_windows:{date:string;period:string}[]; status:'new'|'contacted'|'scheduled'|'won'|'lost'; created_at:string };
const statuses: Lead['status'][] = ['new','contacted','scheduled','won','lost'];

export function AdminPanel() {
  const [leads,setLeads]=useState<Lead[]>([]); const [selected,setSelected]=useState<Lead|null>(null); const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError(''); const supabase=getBrowserSupabase(); const {data:{user}}=await supabase.auth.getUser(); if(!user){window.location.assign('/admin/login');return;} const {data,error}=await supabase.from('leads').select('*').order('created_at',{ascending:false}).limit(250); if(error)setError(error.message); else setLeads((data??[]) as Lead[]); setLoading(false);},[]);
  useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>leads.filter(l=>(status==='all'||l.status===status)&&(`${l.reference_number} ${l.customer_name} ${l.customer_email} ${l.customer_phone} ${l.city}`.toLowerCase().includes(query.toLowerCase()))),[leads,query,status]);
  const counts=useMemo(()=>({new:leads.filter(l=>l.status==='new').length,active:leads.filter(l=>['contacted','scheduled'].includes(l.status)).length,won:leads.filter(l=>l.status==='won').length}),[leads]);
  async function changeStatus(lead:Lead,next:Lead['status']){const {error}=await getBrowserSupabase().from('leads').update({status:next}).eq('id',lead.id); if(error){setError(error.message);return;} setLeads(xs=>xs.map(x=>x.id===lead.id?{...x,status:next}:x)); setSelected(s=>s?.id===lead.id?{...s,status:next}:s);}
  async function signOut(){await getBrowserSupabase().auth.signOut();window.location.assign('/admin/login');}
  return <main className="admin-shell"><header className="admin-header"><div><span className="eyebrow">All Phase Electric</span><h1>Estimate leads</h1></div><button className="secondary-button" onClick={signOut}>Sign out</button></header><section className="kpi-grid"><article><span>New</span><strong>{counts.new}</strong></article><article><span>In follow-up</span><strong>{counts.active}</strong></article><article><span>Won</span><strong>{counts.won}</strong></article></section><section className="admin-toolbar"><input aria-label="Search leads" placeholder="Search name, phone, email or reference" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="secondary-button" onClick={()=>void load()}>Refresh</button></section>{error&&<p role="alert" className="form-error">{error}</p>}{loading?<p>Loading leads…</p>:<div className="lead-layout"><section className="lead-list" aria-label="Lead list">{filtered.length===0?<p>No matching leads.</p>:filtered.map(lead=><button key={lead.id} className={`lead-row ${selected?.id===lead.id?'selected':''}`} onClick={()=>setSelected(lead)}><span><strong>{lead.customer_name}</strong><small>{lead.reference_number} · {lead.job_type}</small></span><span><b className={`status-badge status-${lead.status}`}>{lead.status}</b><small>{new Date(lead.created_at).toLocaleDateString()}</small></span></button>)}</section><aside className="lead-detail">{selected?<><div className="detail-heading"><div><span className="eyebrow">{selected.reference_number}</span><h2>{selected.customer_name}</h2></div><select aria-label="Lead status" value={selected.status} onChange={e=>void changeStatus(selected,e.target.value as Lead['status'])}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="detail-actions"><a className="primary-button" href={`tel:${selected.customer_phone}`}>Call</a><a className="secondary-button" href={`mailto:${selected.customer_email}`}>Email</a></div><dl><dt>Job</dt><dd>{selected.job_type} · {selected.service_type}</dd><dt>Urgency</dt><dd>{selected.urgency}</dd><dt>Location</dt><dd>{selected.street}, {selected.city}, {selected.state} {selected.zip}</dd><dt>Contact</dt><dd>{selected.customer_phone}<br/>{selected.customer_email}<br/>Prefers {selected.preferred_contact}</dd><dt>Description</dt><dd className="preserve">{selected.description}</dd><dt>Preferred window</dt><dd>{selected.preferred_windows?.map(w=>`${w.date} ${w.period}`).join(', ')||'Not specified'}</dd></dl></>:<p>Select a lead to view details.</p>}</aside></div>}</main>;
}
